var arr=[3,6];
arr[234] = "hi";
console.log(arr.length);
console.log(arr[34]);
arr.length = 3;
console.log(arr[34]);
console.log( arr[234] );
console.log( arr.length );
arr.length = 500;
console.log( arr[234] );
console.log( arr.length );
